version: "3"

services:
  db-video:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: video-streaming
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3311:3306"
    volumes:
      - db-data:/var/lib/mysql

  app:
    image: video-streaming-api
    depends_on:
      - db-video
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-video:3306/video-streaming
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"

volumes:
  db-data: